// Generates docs/SCHEME.md from scheme/palaka-hk.json, so the documentation cannot drift from the map.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { schemeData, toTelugu, type GroupId, type SchemeEntry } from '../src/engine';

const inGroup = (group: GroupId) =>
  schemeData.entries.filter((e) => e.group === group).sort((a, b) => a.order - b.order);

const code = (s: string) => '`` ' + s.replace(/\|/g, '\\|') + ' ``';
const show = (e: SchemeEntry) => (e.action === 'zwnj' ? 'U+200C' : e.letter || '(nothing)');
const row = (cells: string[]) => `| ${cells.join(' | ')} |`;
const table = (head: string[], rows: string[][]) =>
  [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');

const vargas: GroupId[] = ['velar', 'palatal', 'retroflex', 'dental', 'labial'];
const examples = ['palaka', 'telugu', 'dEzaM', 'kRSNa', 'jJAnaM', 'gurraM', 'ceTTu', 'sAphT^vEr', 'a_i', 'k_ha', 'l_R', 'idi `PDF` kAdu'];

const doc = `# ${schemeData.name} ${schemeData.version}

<!-- Generated by \`npm run docs:scheme\` from scheme/palaka-hk.json. Do not edit by hand. -->

Palaka-HK is Harvard-Kyoto plus Telugu extensions. It is case-sensitive. One key
sequence gives exactly one Telugu output, and every Telugu text converts back to
exactly one key sequence.

## Vowels

${table(['Key', 'Letter', 'Vowel sign', 'Note'], inGroup('vowels').map((e) => [code(e.key), e.letter, e.sign ? '◌' + e.sign : '(inherent)', e.note ?? '']))}

## Consonants

${table(['Group', '1', '2', '3', '4', '5'], vargas.map((g) => [g, ...inGroup(g).map((e) => `${code(e.key)} ${e.letter}`)]))}

${table(['Key', 'Letter', 'Note'], [...inGroup('other'), ...inGroup('conjuncts')].map((e) => [code(e.key), e.letter, e.note ?? '']))}

## Signs, controls and rare letters

${table(['Key', 'Output', 'Note'], [...inGroup('signs'), ...inGroup('controls'), ...inGroup('rare')].map((e) => [code(e.key), show(e), e.note ?? '']))}

## Digits

Digits stay as 0–9 by default. With the Telugu digits setting they become
${inGroup('digits').map((e) => e.letter).join(' ')}.

## Rules

1. **Longest match first.** At each position the longest key wins: \`lRR\` before \`lR\` before \`l\`, \`kh\` before \`k\`, \`ai\` before \`a\`.
2. **After a consonant**, a vowel key writes the vowel sign (nothing for \`a\`), a consonant key forms a conjunct through the virama, and anything else, including the end of the text, leaves a visible pollu.
3. **Elsewhere** a vowel key writes the independent letter.
4. \`x\` has no sound of its own; it only marks a variant of the key before it (\`rx\`, \`Mx\`, \`Lx\` …).
5. \`_\` splits two keys that would otherwise merge and outputs nothing. It never changes the syllable: \`l_R\` is ల + ృ.
6. \`^\` writes a zero-width non-joiner, keeping the pollu visible instead of forming a conjunct.
7. \`__\` closes the syllable, so that a following vowel stays independent. Ordinary text never needs it.
8. Text between backticks is copied unchanged with the backticks removed. An empty pair gives one literal backtick. A span that is not closed ends at the end of its line.
9. Anything not in the map is copied unchanged; unmapped Latin letters (\`f\`, \`q\`, \`w\`, a stray \`x\`) raise a warning.

## Examples

${table(['Typed', 'Result'], examples.map((r) => [code(r), toTelugu(r)]))}
`;

writeFileSync(fileURLToPath(new URL('../docs/SCHEME.md', import.meta.url)), doc, 'utf8');
console.log('docs/SCHEME.md written.');
