// The text of docs/SCHEME.md, built from scheme/palaka-hk.json. A test compares it with the file.
import { schemeData, toTelugu, type GroupId, type SchemeEntry } from '../src/engine';
import { EXAMPLES, RULES } from '../src/help/rules';

const inGroup = (group: GroupId) =>
  schemeData.entries.filter((e) => e.group === group).sort((a, b) => a.order - b.order);

const code = (s: string) => '`` ' + s.replace(/\|/g, '\\|') + ' ``';
const show = (e: SchemeEntry) => (e.action === 'zwnj' ? 'U+200C' : e.letter || '(nothing)');
const row = (cells: string[]) => `| ${cells.join(' | ')} |`;
const table = (head: string[], rows: string[][]) =>
  [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');

const vargas: GroupId[] = ['velar', 'palatal', 'retroflex', 'dental', 'labial'];
export const schemeDoc = `# ${schemeData.name} ${schemeData.version}

<!-- Generated by \`npm run docs:scheme\` from scheme/palaka-hk.json. Do not edit by hand. -->

Palaka-HK is Harvard-Kyoto plus Telugu extensions. It is case-sensitive. One key
sequence gives exactly one Telugu output, and every Telugu text converts back to
exactly one key sequence.

## Vowels

${table(['Key', 'Letter', 'Vowel sign', 'Note'], inGroup('vowels').map((e) => [code(e.key), e.letter, e.sign ? '◌' + e.sign : '(inherent)', e.note ?? '']))}

## Consonants

${table(['Group', '1', '2', '3', '4', '5'], vargas.map((g) => [g, ...inGroup(g).map((e) => `${code(e.key)} ${e.letter}`)]))}

${table(['Key', 'Letter', 'Note'], [...inGroup('other'), ...inGroup('conjuncts')].map((e) => [code(e.key), e.letter, e.note ?? '']))}

## Signs, controls and rare letters

${table(['Key', 'Output', 'Note'], [...inGroup('signs'), ...inGroup('controls'), ...inGroup('rare')].map((e) => [code(e.key), show(e), e.note ?? '']))}

## Digits

Digits stay as 0–9 by default. With the Telugu digits setting they become
${inGroup('digits').map((e) => e.letter).join(' ')}.

## Rules

${RULES.map((rule, i) => `${i + 1}. ${rule}`).join('\n')}

## Examples

${table(['Typed', 'Result'], EXAMPLES.map((r) => [code(r), toTelugu(r)]))}
`;
